// Generated by scripts/build.py. Do not edit.
// QenTerra Design System 1.2.0
import Foundation

public enum QDSGeneratedTokens {
    public static let version = "1.2.0"

    public enum Space {
        public static let value0: Double = 0
        public static let value1: Double = 4
        public static let value2: Double = 8
        public static let value3: Double = 12
        public static let value4: Double = 16
        public static let value5: Double = 20
        public static let value6: Double = 24
        public static let value8: Double = 32
        public static let value10: Double = 40
        public static let value12: Double = 48
        public static let value16: Double = 64
        public static let value20: Double = 80
    }

    public enum Radius {
        public static let none: Double = 0
        public static let control: Double = 6
        public static let group: Double = 10
        public static let panel: Double = 14
        public static let hero: Double = 18
        public static let floating: Double = 20
        public static let pill: Double = 999
    }

    public enum Stroke {
        public static let hairline: Double = 0.5
        public static let `default`: Double = 1
        public static let focus: Double = 2
        public static let emphasis: Double = 2
    }

    public enum Size {
        public static let controlCompact: Double = 28
        public static let controlStandard: Double = 32
        public static let controlProminent: Double = 40
        public static let targetPointer: Double = 28
        public static let targetTouch: Double = 44
        public static let rowCompact: Double = 40
        public static let rowStandard: Double = 48
        public static let rowComfortable: Double = 56
        public static let railCompact: Double = 64
        public static let sidebarCompact: Double = 214
        public static let sidebarStandard: Double = 256
        public static let contentReadable: Double = 760
        public static let iconXS: Double = 12
        public static let iconS: Double = 14
        public static let iconM: Double = 16
        public static let iconL: Double = 20
        public static let iconXL: Double = 24
    }

    public enum MotionSeconds {
        public static let instant: Double = 0.0
        public static let press: Double = 0.08
        public static let hover: Double = 0.1
        public static let floatingFast: Double = 0.12
        public static let present: Double = 0.14
        public static let replace: Double = 0.15
        public static let dismiss: Double = 0.16
        public static let disclosure: Double = 0.18
        public static let spatial: Double = 0.22
        public static let spatialLong: Double = 0.24
    }

    public enum SemanticName {
        public static let actionPrimary = "action.primary"
        public static let actionPrimarycontent = "action.primaryContent"
        public static let actionQuietcontent = "action.quietContent"
        public static let actionSecondary = "action.secondary"
        public static let actionSecondarycontent = "action.secondaryContent"
        public static let borderDefault = "border.default"
        public static let borderFocus = "border.focus"
        public static let borderStrong = "border.strong"
        public static let borderSubtle = "border.subtle"
        public static let fillDisabled = "fill.disabled"
        public static let fillHover = "fill.hover"
        public static let fillPressed = "fill.pressed"
        public static let fillScrim = "fill.scrim"
        public static let fillSelected = "fill.selected"
        public static let fillSelectedstrong = "fill.selectedStrong"
        public static let stateDestructive = "state.destructive"
        public static let stateInformative = "state.informative"
        public static let stateRecording = "state.recording"
        public static let stateSuccess = "state.success"
        public static let stateWarning = "state.warning"
        public static let surfaceChrome = "surface.chrome"
        public static let surfaceContent = "surface.content"
        public static let surfaceInverted = "surface.inverted"
        public static let surfaceOverlay = "surface.overlay"
        public static let surfaceRaised = "surface.raised"
        public static let surfaceSecondary = "surface.secondary"
        public static let textDisabled = "text.disabled"
        public static let textInverted = "text.inverted"
        public static let textLink = "text.link"
        public static let textPrimary = "text.primary"
        public static let textSecondary = "text.secondary"
        public static let textTertiary = "text.tertiary"
    }
}
