// Generated by scripts/generate.py. Do not edit.
// Design System 5.3.0
import Foundation

public enum GeneratedTokens {
    public static let version = "5.3.0"

    public enum Space {
        public static let value0: Double = 0
        public static let value1: Double = 4
        public static let value2: Double = 8
        public static let value3: Double = 12
        public static let value4: Double = 16
        public static let value5: Double = 20
        public static let value6: Double = 24
        public static let value8: Double = 32
        public static let value10: Double = 40
        public static let value12: Double = 48
        public static let value16: Double = 64
        public static let value20: Double = 80
    }

    public enum Radius {
        public static let none: Double = 0
        public static let control: Double = 6
        public static let group: Double = 10
        public static let panel: Double = 14
        public static let hero: Double = 18
        public static let floating: Double = 20
        public static let pill: Double = 999
    }

    public enum Stroke {
        public static let hairline: Double = 0.5
        public static let `default`: Double = 1
        public static let focus: Double = 2
        public static let emphasis: Double = 2
    }

    public enum Size {
        public static let controlCompact: Double = 28
        public static let controlStandard: Double = 32
        public static let controlProminent: Double = 40
        public static let targetPointer: Double = 28
        public static let targetTouch: Double = 44
        public static let rowCompact: Double = 40
        public static let rowStandard: Double = 48
        public static let rowComfortable: Double = 56
        public static let railCompact: Double = 64
        public static let sidebarCompact: Double = 214
        public static let sidebarStandard: Double = 256
        public static let contentReadable: Double = 760
        public static let iconXS: Double = 12
        public static let iconS: Double = 14
        public static let iconM: Double = 16
        public static let iconL: Double = 20
        public static let iconXL: Double = 24
    }

    public enum Opacity {
        public static let disabled: Double = 0.42
        public static let faint: Double = 0.46
        public static let secondary: Double = 0.68
        public static let pressed: Double = 0.82
        public static let hover: Double = 0.045
        public static let selection: Double = 0.085
        public static let selectionStrong: Double = 0.14
        public static let dividerDark: Double = 0.13
        public static let dividerLight: Double = 0.12
        public static let scrim: Double = 0.46
    }

    public enum ZIndex {
        public static let content: Double = 0
        public static let chrome: Double = 10
        public static let popover: Double = 30
        public static let modal: Double = 40
        public static let toast: Double = 50
        public static let tooltip: Double = 60
    }

    public enum MotionSeconds {
        public static let instant: Double = 0.0
        public static let press: Double = 0.08
        public static let hover: Double = 0.1
        public static let floatingFast: Double = 0.12
        public static let present: Double = 0.14
        public static let replace: Double = 0.15
        public static let dismiss: Double = 0.16
        public static let disclosure: Double = 0.18
        public static let spatial: Double = 0.22
        public static let spatialLong: Double = 0.24
    }

    public enum SemanticName {
        public static let actionPrimary = "action.primary"
        public static let actionPrimaryContent = "action.primaryContent"
        public static let actionQuietContent = "action.quietContent"
        public static let actionSecondary = "action.secondary"
        public static let actionSecondaryContent = "action.secondaryContent"
        public static let borderDefault = "border.default"
        public static let borderFocus = "border.focus"
        public static let borderStrong = "border.strong"
        public static let borderSubtle = "border.subtle"
        public static let fillDisabled = "fill.disabled"
        public static let fillHover = "fill.hover"
        public static let fillPressed = "fill.pressed"
        public static let fillScrim = "fill.scrim"
        public static let fillSelected = "fill.selected"
        public static let fillSelectedStrong = "fill.selectedStrong"
        public static let shadowFloating = "shadow.floating"
        public static let shadowOverlay = "shadow.overlay"
        public static let shadowRaised = "shadow.raised"
        public static let stateDestructive = "state.destructive"
        public static let stateInformative = "state.informative"
        public static let stateRecording = "state.recording"
        public static let stateSuccess = "state.success"
        public static let stateWarning = "state.warning"
        public static let surfaceChrome = "surface.chrome"
        public static let surfaceContent = "surface.content"
        public static let surfaceInverted = "surface.inverted"
        public static let surfaceOverlay = "surface.overlay"
        public static let surfaceRaised = "surface.raised"
        public static let surfaceSecondary = "surface.secondary"
        public static let textDisabled = "text.disabled"
        public static let textInverted = "text.inverted"
        public static let textLink = "text.link"
        public static let textPrimary = "text.primary"
        public static let textSecondary = "text.secondary"
        public static let textTertiary = "text.tertiary"
    }

    public enum Color {
        public static let actionPrimary = DesignColorValue(light: "#1A1A1C", dark: "#FFFFFF")
        public static let actionPrimaryContent = DesignColorValue(light: "#FFFFFF", dark: "#171719")
        public static let actionQuietContent = DesignColorValue(light: "#27272B", dark: "#E8E8EC")
        public static let actionSecondary = DesignColorValue(light: "#E8E8EC", dark: "#27272B")
        public static let actionSecondaryContent = DesignColorValue(light: "#1A1A1C", dark: "#FFFFFF")
        public static let borderDefault = DesignColorValue(light: "rgba(15, 15, 17, 0.12)", dark: "rgba(255, 255, 255, 0.13)")
        public static let borderFocus = DesignColorValue(light: "#1A1A1C", dark: "#FFFFFF")
        public static let borderStrong = DesignColorValue(light: "rgba(15, 15, 17, 0.22)", dark: "rgba(255, 255, 255, 0.24)")
        public static let borderSubtle = DesignColorValue(light: "rgba(15, 15, 17, 0.08)", dark: "rgba(255, 255, 255, 0.07)")
        public static let fillDisabled = DesignColorValue(light: "rgba(15, 15, 17, 0.04)", dark: "rgba(255, 255, 255, 0.04)")
        public static let fillHover = DesignColorValue(light: "rgba(15, 15, 17, 0.045)", dark: "rgba(255, 255, 255, 0.045)")
        public static let fillPressed = DesignColorValue(light: "rgba(15, 15, 17, 0.085)", dark: "rgba(255, 255, 255, 0.085)")
        public static let fillScrim = DesignColorValue(light: "rgba(15, 15, 17, 0.46)", dark: "rgba(0, 0, 0, 0.46)")
        public static let fillSelected = DesignColorValue(light: "rgba(15, 15, 17, 0.075)", dark: "rgba(255, 255, 255, 0.085)")
        public static let fillSelectedStrong = DesignColorValue(light: "rgba(15, 15, 17, 0.14)", dark: "rgba(255, 255, 255, 0.14)")
        public static let shadowFloating = DesignColorValue(light: "0 16px 44px rgba(15, 15, 17, 0.18)", dark: "0 16px 44px rgba(0, 0, 0, 0.34)")
        public static let shadowOverlay = DesignColorValue(light: "0 20px 60px rgba(15, 15, 17, 0.18)", dark: "0 20px 60px rgba(0, 0, 0, 0.36)")
        public static let shadowRaised = DesignColorValue(light: "0 20px 60px rgba(15, 15, 17, 0.14)", dark: "0 20px 60px rgba(0, 0, 0, 0.28)")
        public static let stateDestructive = DesignColorValue(light: "#D84A42", dark: "#E5695E")
        public static let stateInformative = DesignColorValue(light: "#2468C9", dark: "#68A4F1")
        public static let stateRecording = DesignColorValue(light: "#E5695E", dark: "#E5695E")
        public static let stateSuccess = DesignColorValue(light: "#267A3A", dark: "#5EC26F")
        public static let stateWarning = DesignColorValue(light: "#B96200", dark: "#F0A342")
        public static let surfaceChrome = DesignColorValue(light: "#FAFAFB", dark: "#1A1A1C")
        public static let surfaceContent = DesignColorValue(light: "#F4F4F6", dark: "#171719")
        public static let surfaceInverted = DesignColorValue(light: "#171719", dark: "#F4F4F6")
        public static let surfaceOverlay = DesignColorValue(light: "#FFFFFF", dark: "#27272B")
        public static let surfaceRaised = DesignColorValue(light: "#E0E0E6", dark: "#27272B")
        public static let surfaceSecondary = DesignColorValue(light: "#E8E8EC", dark: "#202023")
        public static let textDisabled = DesignColorValue(light: "#94949D", dark: "#6A6A73")
        public static let textInverted = DesignColorValue(light: "#FFFFFF", dark: "#171719")
        public static let textLink = DesignColorValue(light: "#1A1A1C", dark: "#FFFFFF")
        public static let textPrimary = DesignColorValue(light: "#1A1A1C", dark: "#FFFFFF")
        public static let textSecondary = DesignColorValue(light: "#56565E", dark: "#B9B9C0")
        public static let textTertiary = DesignColorValue(light: "#6A6A73", dark: "#94949D")
    }

    public enum Typography {
        public static let display = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 40, lineHeight: 48, weight: 650, tracking: -0.8, transform: nil, numeric: nil)
        public static let screenTitle = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 24, lineHeight: 30, weight: 600, tracking: -0.35, transform: nil, numeric: nil)
        public static let modalTitle = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 20, lineHeight: 26, weight: 600, tracking: -0.2, transform: nil, numeric: nil)
        public static let sectionTitle = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 15, lineHeight: 20, weight: 600, tracking: -0.08, transform: nil, numeric: nil)
        public static let body = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 14, lineHeight: 20, weight: 400, tracking: 0, transform: nil, numeric: nil)
        public static let bodyEmphasized = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 14, lineHeight: 20, weight: 550, tracking: 0, transform: nil, numeric: nil)
        public static let row = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 13, lineHeight: 18, weight: 400, tracking: 0, transform: nil, numeric: nil)
        public static let rowEmphasized = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 13, lineHeight: 18, weight: 550, tracking: 0, transform: nil, numeric: nil)
        public static let supporting = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 12, lineHeight: 17, weight: 400, tracking: 0, transform: nil, numeric: nil)
        public static let metadata = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 11, lineHeight: 15, weight: 400, tracking: 0.08, transform: nil, numeric: nil)
        public static let compactMetadata = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 10, lineHeight: 14, weight: 500, tracking: 0.16, transform: nil, numeric: nil)
        public static let eyebrow = DesignTypographyValue(family: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', sans-serif", size: 11, lineHeight: 15, weight: 600, tracking: 0.7, transform: "uppercase", numeric: nil)
        public static let keycap = DesignTypographyValue(family: "ui-rounded, 'SF Pro Rounded', -apple-system, sans-serif", size: 12, lineHeight: 16, weight: 500, tracking: 0, transform: nil, numeric: nil)
        public static let monospacedData = DesignTypographyValue(family: "ui-monospace, 'SF Mono', SFMono-Regular, Menlo, monospace", size: 12, lineHeight: 17, weight: 500, tracking: 0, transform: nil, numeric: "tabular")
    }

    public enum Motion {
        public static let feedbackPress = DesignMotionValue(seconds: 0.08, curve: [0.2, 0, 0, 1], properties: ["opacity", "scale<=0.98"])
        public static let feedbackHover = DesignMotionValue(seconds: 0.1, curve: [0.2, 0, 0, 1], properties: ["background", "foreground"])
        public static let stateReplace = DesignMotionValue(seconds: 0.15, curve: [0.2, 0, 0, 1], properties: ["opacity"])
        public static let floatingPresent = DesignMotionValue(seconds: 0.14, curve: [0.16, 1, 0.3, 1], properties: ["opacity", "scale:0.98->1"])
        public static let floatingDismiss = DesignMotionValue(seconds: 0.16, curve: [0.4, 0, 1, 1], properties: ["opacity", "scale:1->0.99"])
        public static let disclosureToggle = DesignMotionValue(seconds: 0.18, curve: [0.2, 0, 0, 1], properties: ["height", "opacity"])
        public static let navigationSpatial = DesignMotionValue(seconds: 0.22, curve: [0.2, 0, 0, 1], properties: ["transform", "opacity"])
        public static let progressContinuous = DesignMotionValue(seconds: 0, curve: [0, 0, 1, 1], properties: ["measured-progress"])
    }

    public enum Component {
        public static let buttonHeightsCompact = DesignComponentMetric(points: 28)
        public static let buttonHeightsProminent = DesignComponentMetric(points: 40)
        public static let buttonHeightsStandard = DesignComponentMetric(points: 32)
        public static let buttonIconGap = DesignComponentMetric(points: 8)
        public static let buttonPaddingXCompact = DesignComponentMetric(points: 10)
        public static let buttonPaddingXProminent = DesignComponentMetric(points: 16)
        public static let buttonPaddingXStandard = DesignComponentMetric(points: 12)
        public static let buttonRadius = DesignComponentMetric(points: 6)
        public static let fieldHeight = DesignComponentMetric(points: 32)
        public static let fieldPaddingX = DesignComponentMetric(points: 12)
        public static let fieldRadius = DesignComponentMetric(points: 6)
        public static let groupGap = DesignComponentMetric(points: 12)
        public static let groupPadding = DesignComponentMetric(points: 16)
        public static let groupRadius = DesignComponentMetric(points: 10)
        public static let interactiveRowGap = DesignComponentMetric(points: 12)
        public static let interactiveRowHeightsComfortable = DesignComponentMetric(points: 56)
        public static let interactiveRowHeightsCompact = DesignComponentMetric(points: 40)
        public static let interactiveRowHeightsStandard = DesignComponentMetric(points: 48)
        public static let interactiveRowPaddingX = DesignComponentMetric(points: 12)
        public static let interactiveRowRadius = DesignComponentMetric(points: 6)
        public static let keycapGap = DesignComponentMetric(points: 4)
        public static let keycapHeight = DesignComponentMetric(points: 24)
        public static let keycapPaddingX = DesignComponentMetric(points: 7)
        public static let keycapRadius = DesignComponentMetric(points: 6)
        public static let navigationItemHeight = DesignComponentMetric(points: 40)
        public static let navigationMinimumIconTarget = DesignComponentMetric(points: 28)
        public static let navigationRailCompact = DesignComponentMetric(points: 64)
        public static let navigationSidebarCompact = DesignComponentMetric(points: 214)
        public static let navigationSidebarStandard = DesignComponentMetric(points: 256)
        public static let overlayDialogReadableWidth = DesignComponentMetric(points: 480)
        public static let overlayPopoverMaxWidth = DesignComponentMetric(points: 360)
        public static let overlaySheetReadableWidth = DesignComponentMetric(points: 640)
        public static let panelGap = DesignComponentMetric(points: 16)
        public static let panelPadding = DesignComponentMetric(points: 20)
        public static let panelRadius = DesignComponentMetric(points: 14)
        public static let statusGap = DesignComponentMetric(points: 6)
        public static let statusIconSize = DesignComponentMetric(points: 14)
        public static let tableColumnGap = DesignComponentMetric(points: 16)
        public static let tableHeaderHeight = DesignComponentMetric(points: 32)
        public static let tableRowHeightsCompact = DesignComponentMetric(points: 40)
        public static let tableRowHeightsStandard = DesignComponentMetric(points: 48)
    }
}
