// Generated by scripts/generate.py. Do not edit.
// Design System 5.1.0

public enum DesignIcon: String, CaseIterable, Sendable {
    case accessibility = "accessibility"
    case search = "magnifyingglass"
    case menu = "line.3.horizontal"
    case globe = "globe"
    case chevron = "chevron.down"
    case add = "plus"
    case close = "xmark"
    case delete = "trash"
    case success = "checkmark.circle"
    case warning = "exclamationmark.triangle"
    case error = "xmark.circle"
    case information = "info.circle"

    public var systemName: String { rawValue }
}
