// Generated by scripts/generate.py. Do not edit.
// Design System 1.0.1
import Foundation

public enum GeneratedProductProfiles {
    public static let cadence = DesignProductMetrics(
        textStack: 4,
        compactGap: 8,
        controlGap: 12,
        contentGap: 16,
        panelInset: 20,
        pageInset: 24,
        sectionGap: 32,
        rowHeight: 48,
        readableContentWidth: 760
    )
}
