"""Token loading, reference resolution, and platform adapter generation."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


REFERENCE = re.compile(r"^\{([^}]+)}$")


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def get_path(mapping: dict[str, Any], dotted: str) -> Any:
    current: Any = mapping
    for segment in dotted.split("."):
        if not isinstance(current, dict) or segment not in current:
            raise KeyError(f"Unknown token reference: {dotted}")
        current = current[segment]
    return current


def resolve(value: Any, foundation: dict[str, Any]) -> Any:
    if isinstance(value, str):
        match = REFERENCE.match(value)
        if match:
            return resolve(get_path(foundation, match.group(1)), foundation)
    return value


def kebab(value: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value)
    return re.sub(r"[^a-zA-Z0-9]+", "-", value).strip("-").lower()


def swift_name(value: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", value)
    return parts[0].lower() + "".join(part.capitalize() for part in parts[1:])


def flatten(mapping: dict[str, Any], prefix: tuple[str, ...] = ()) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in mapping.items():
        path = (*prefix, key)
        if isinstance(value, dict):
            result.update(flatten(value, path))
        else:
            result[".".join(path)] = value
    return result


def css_value(value: Any) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return f"{value}px"
    return str(value)


def generate_css(
    foundation: dict[str, Any], semantic: dict[str, Any], typography: dict[str, Any], motion: dict[str, Any]
) -> str:
    light = flatten(semantic["modes"]["light"])
    dark = flatten(semantic["modes"]["dark"])
    type_roles = typography["roles"]

    def mode_lines(values: dict[str, Any]) -> list[str]:
        return [
            f"  --qds-{kebab(name)}: {css_value(resolve(value, foundation))};"
            for name, value in sorted(values.items())
        ]

    lines = [
        "/* Generated by scripts/build.py. Do not edit. */",
        f"/* QenTerra Design System {foundation['meta']['version']} */",
        ":root, [data-theme=\"light\"] {",
        *mode_lines(light),
    ]

    for name, value in flatten({key: foundation[key] for key in ("space", "radius", "stroke", "size")}).items():
        lines.append(f"  --qds-{kebab(name)}: {css_value(value)};")

    for name, role in type_roles.items():
        role_name = kebab(name)
        family = role.get("family", "sans")
        lines.extend(
            [
                f"  --qds-type-{role_name}-size: {role['size']}px;",
                f"  --qds-type-{role_name}-line: {role['line']}px;",
                f"  --qds-type-{role_name}-weight: {role['weight']};",
                f"  --qds-type-{role_name}-tracking: {role['tracking']}px;",
                f"  --qds-type-{role_name}-family: {typography['family'][family]};",
            ]
        )

    for name, value in motion["durationMs"].items():
        lines.append(f"  --qds-motion-{kebab(name)}: {value}ms;")
    for name, curve in motion["curve"].items():
        lines.append(f"  --qds-ease-{kebab(name)}: cubic-bezier({', '.join(str(v) for v in curve)});")
    lines.append("}")

    lines.extend(["[data-theme=\"dark\"] {", *mode_lines(dark), "}"])
    lines.extend(
        [
            "@media (prefers-color-scheme: dark) {",
            "  :root:not([data-theme=\"light\"]):not([data-theme=\"dark\"]) {",
            *[f"  {line}" for line in mode_lines(dark)],
            "  }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def generate_swift(foundation: dict[str, Any], semantic: dict[str, Any], motion: dict[str, Any]) -> str:
    space = foundation["space"]
    radius = foundation["radius"]
    sizes = foundation["size"]
    durations = motion["durationMs"]

    def constants(mapping: dict[str, Any], multiplier: str = "") -> list[str]:
        result = []
        for name, value in mapping.items():
            identifier = swift_name(f"value{name}") if name[0].isdigit() else swift_name(name)
            result.append(f"        public static let {identifier}: Double = {value}{multiplier}")
        return result

    return "\n".join(
        [
            "// Generated by scripts/build.py. Do not edit.",
            f"// QenTerra Design System {foundation['meta']['version']}",
            "import Foundation",
            "",
            "public enum QDSGeneratedTokens {",
            "    public enum Space {",
            *constants(space),
            "    }",
            "",
            "    public enum Radius {",
            *constants(radius),
            "    }",
            "",
            "    public enum Size {",
            *constants(sizes),
            "    }",
            "",
            "    public enum MotionSeconds {",
            *constants({key: round(value / 1000, 3) for key, value in durations.items()}),
            "    }",
            "",
            "    public enum SemanticName {",
            *[
                f'        public static let {swift_name(name)} = "{name}"'
                for name in sorted(flatten(semantic["modes"]["light"]))
            ],
            "    }",
            "}",
            "",
        ]
    )


def generate_token_reference(token_files: list[tuple[str, dict[str, Any]]]) -> str:
    lines = [
        "# Generated token reference",
        "",
        "Generated by `scripts/build.py`. Do not edit directly.",
        "",
    ]
    for filename, data in token_files:
        lines.extend([f"## {data['meta']['name']}", "", data["meta"]["description"], ""])
        for name, value in sorted(flatten({k: v for k, v in data.items() if k not in {"$schema", "meta"}}).items()):
            display = json.dumps(value, ensure_ascii=False) if not isinstance(value, str) else value
            lines.append(f"- `{name}`: `{display}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
