"""Token loading, reference resolution, and platform adapter generation."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


REFERENCE = re.compile(r"^\{([^}]+)}$")
COMPONENT_VALUE_UNITS = {
    "panel.lyrics.followDurationMs": "milliseconds",
    "panel.lyrics.inactiveOpacity": "unitless",
}


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def get_path(mapping: dict[str, Any], dotted: str) -> Any:
    current: Any = mapping
    for segment in dotted.split("."):
        if not isinstance(current, dict) or segment not in current:
            raise KeyError(f"Unknown token reference: {dotted}")
        current = current[segment]
    return current


def resolve(value: Any, foundation: dict[str, Any]) -> Any:
    if isinstance(value, str):
        match = REFERENCE.match(value)
        if match:
            return resolve(get_path(foundation, match.group(1)), foundation)
    return value


def kebab(value: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value)
    return re.sub(r"[^a-zA-Z0-9]+", "-", value).strip("-").lower()


def swift_name(value: str) -> str:
    parts = [part for part in re.split(r"[^a-zA-Z0-9]+", value) if part]
    first = parts[0]
    identifier = first[:1].lower() + first[1:] + "".join(part[:1].upper() + part[1:] for part in parts[1:])
    keywords = {
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
        "init", "inout", "internal", "let", "open", "operator", "private", "protocol", "public",
        "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "continue",
        "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat",
        "return", "switch", "where", "while", "as", "catch", "false", "is", "nil", "super",
        "self", "Self", "throw", "throws", "true", "try",
    }
    return f"`{identifier}`" if identifier in keywords else identifier


def flatten(mapping: dict[str, Any], prefix: tuple[str, ...] = ()) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in mapping.items():
        path = (*prefix, key)
        if isinstance(value, dict):
            result.update(flatten(value, path))
        else:
            result[".".join(path)] = value
    return result


def css_value(value: Any) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return f"{value}px"
    return str(value)


def component_value_unit(name: str) -> str:
    if name in COMPONENT_VALUE_UNITS:
        return COMPONENT_VALUE_UNITS[name]
    if name.endswith(("Opacity", "DurationMs")):
        raise ValueError(f"component token {name!r} needs an explicit semantic unit")
    return "points"


def generate_css(
    foundation: dict[str, Any],
    semantic: dict[str, Any],
    typography: dict[str, Any],
    motion: dict[str, Any],
    components: dict[str, Any],
) -> str:
    light = flatten(semantic["modes"]["light"])
    dark = flatten(semantic["modes"]["dark"])
    type_roles = typography["roles"]

    def mode_lines(values: dict[str, Any]) -> list[str]:
        return [
            f"  --design-system-{kebab(name)}: {css_value(resolve(value, foundation))};"
            for name, value in sorted(values.items())
        ]

    lines = [
        "/* Generated by scripts/generate.py. Do not edit. */",
        f"/* Design System {foundation['meta']['version']} */",
        ":root, [data-theme=\"light\"] {",
        *mode_lines(light),
    ]

    for name, value in flatten(
        {key: foundation[key] for key in ("space", "radius", "stroke", "size")}
    ).items():
        lines.append(f"  --design-system-{kebab(name)}: {css_value(value)};")
    for name, value in flatten({key: foundation[key] for key in ("opacity", "zIndex")}).items():
        lines.append(f"  --design-system-{kebab(name)}: {value};")

    for name, role in type_roles.items():
        role_name = kebab(name)
        family = role.get("family", "sans")
        lines.extend(
            [
                f"  --design-system-type-{role_name}-size: {role['size']}px;",
                f"  --design-system-type-{role_name}-line: {role['line']}px;",
                f"  --design-system-type-{role_name}-weight: {role['weight']};",
                f"  --design-system-type-{role_name}-tracking: {role['tracking']}px;",
                f"  --design-system-type-{role_name}-family: {typography['family'][family]};",
            ]
        )

    for name, value in motion["durationMs"].items():
        lines.append(f"  --design-system-motion-{kebab(name)}: {value}ms;")
    for name, curve in motion["curve"].items():
        lines.append(f"  --design-system-ease-{kebab(name)}: cubic-bezier({', '.join(str(v) for v in curve)});")
    for name, value in sorted(
        flatten({key: value for key, value in components.items() if key not in {"$schema", "meta", "extensions"}}).items()
    ):
        if isinstance(value, str) and REFERENCE.match(value):
            value = resolve(value, foundation)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            unit = component_value_unit(name)
            rendered = {
                "points": css_value(value),
                "unitless": str(value),
                "milliseconds": f"{value}ms",
            }[unit]
            lines.append(f"  --design-system-component-{kebab(name)}: {rendered};")
    lines.append("}")

    lines.extend(["[data-theme=\"dark\"] {", *mode_lines(dark), "}"])
    lines.extend(
        [
            "@media (prefers-color-scheme: dark) {",
            "  :root:not([data-theme=\"light\"]):not([data-theme=\"dark\"]) {",
            *[f"  {line}" for line in mode_lines(dark)],
            "  }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def generate_swift(
    foundation: dict[str, Any],
    semantic: dict[str, Any],
    typography: dict[str, Any],
    motion: dict[str, Any],
    components: dict[str, Any],
) -> str:
    space = foundation["space"]
    radius = foundation["radius"]
    stroke = foundation["stroke"]
    sizes = foundation["size"]
    opacity = foundation["opacity"]
    z_index = foundation["zIndex"]
    durations = motion["durationMs"]

    def constants(mapping: dict[str, Any], multiplier: str = "") -> list[str]:
        result = []
        for name, value in mapping.items():
            identifier = swift_name(f"value{name}") if name[0].isdigit() else swift_name(name)
            result.append(f"        public static let {identifier}: Double = {value}{multiplier}")
        return result

    color_light = flatten(semantic["modes"]["light"])
    color_dark = flatten(semantic["modes"]["dark"])

    color_lines = []
    for name in sorted(color_light):
        light = resolve(color_light[name], foundation)
        dark = resolve(color_dark[name], foundation)
        color_lines.append(
            f'        public static let {swift_name(name)} = DesignColorValue(light: "{light}", dark: "{dark}")'
        )

    typography_lines = []
    for name, role in typography["roles"].items():
        family = role.get("family", "sans")
        transform = role.get("transform")
        numeric = role.get("numeric")
        typography_lines.append(
            "        public static let "
            f"{swift_name(name)} = DesignTypographyValue("
            f"family: {json.dumps(typography['family'][family])}, size: {role['size']}, "
            f"lineHeight: {role['line']}, weight: {role['weight']}, tracking: {role['tracking']}, "
            f"transform: {json.dumps(transform) if transform else 'nil'}, "
            f"numeric: {json.dumps(numeric) if numeric else 'nil'})"
        )

    motion_lines = []
    for name, event in motion["events"].items():
        duration = motion["durationMs"][event["duration"]] / 1000
        curve = motion["curve"][event["curve"]]
        properties = ", ".join(json.dumps(item) for item in event["properties"])
        motion_lines.append(
            f"        public static let {swift_name(name)} = DesignMotionValue("
            f"seconds: {duration:g}, curve: [{', '.join(f'{item:g}' for item in curve)}], "
            f"properties: [{properties}])"
        )

    component_values = flatten(
        {key: value for key, value in components.items() if key not in {"$schema", "meta", "extensions"}}
    )
    component_lines = []
    for name, value in sorted(component_values.items()):
        if isinstance(value, str) and REFERENCE.match(value):
            value = resolve(value, foundation)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            unit = component_value_unit(name)
            initializer = {
                "points": f"DesignComponentMetric(points: {value})",
                "unitless": f"DesignComponentOpacity(value: {value})",
                "milliseconds": f"DesignComponentDuration(milliseconds: {value})",
            }[unit]
            component_lines.append(f"        public static let {swift_name(name)} = {initializer}")

    return "\n".join(
        [
            "// Generated by scripts/generate.py. Do not edit.",
            f"// Design System {foundation['meta']['version']}",
            "import Foundation",
            "",
            "public enum GeneratedTokens {",
            f'    public static let version = "{foundation["meta"]["version"]}"',
            "",
            "    public enum Space {",
            *constants(space),
            "    }",
            "",
            "    public enum Radius {",
            *constants(radius),
            "    }",
            "",
            "    public enum Stroke {",
            *constants(stroke),
            "    }",
            "",
            "    public enum Size {",
            *constants(sizes),
            "    }",
            "",
            "    public enum Opacity {",
            *constants(opacity),
            "    }",
            "",
            "    public enum ZIndex {",
            *constants(z_index),
            "    }",
            "",
            "    public enum MotionSeconds {",
            *constants({key: round(value / 1000, 3) for key, value in durations.items()}),
            "    }",
            "",
            "    public enum SemanticName {",
            *[
                f'        public static let {swift_name(name)} = "{name}"'
                for name in sorted(flatten(semantic["modes"]["light"]))
            ],
            "    }",
            "",
            "    public enum Color {",
            *color_lines,
            "    }",
            "",
            "    public enum Typography {",
            *typography_lines,
            "    }",
            "",
            "    public enum Motion {",
            *motion_lines,
            "    }",
            "",
            "    public enum Component {",
            *component_lines,
            "    }",
            "}",
            "",
        ]
    )


def generate_swift_product_profiles(
    products: dict[str, Any],
    platforms: dict[str, Any],
    components: dict[str, Any],
) -> str:
    """Generate product metrics after checking their native component contract."""
    profile = products.get("immersiveContent", {}).get("cadence")
    if not isinstance(profile, dict):
        raise ValueError("tokens/products.json is missing the Cadence profile")
    if profile.get("archetype") != "immersive-content":
        raise ValueError("Cadence must use the immersive-content archetype")
    if profile.get("density") != "standard":
        raise ValueError("Cadence must use standard density")

    platform_name = profile.get("platform")
    platform = platforms.get(platform_name)
    if not isinstance(platform, dict):
        raise ValueError(f"tokens/platforms.json is missing {platform_name}")
    requirements = platform.get("requirements")
    if not isinstance(requirements, list) or "AppKit dynamic colors" not in requirements:
        raise ValueError("macOS must declare AppKit dynamic colors")

    panel = components.get("panel")
    media_table = components.get("table", {}).get("media") if isinstance(components.get("table"), dict) else None
    if not isinstance(panel, dict) or not all(
        isinstance(panel.get(name), dict) for name in ("artwork", "player", "lyrics", "about")
    ) or not isinstance(media_table, dict):
        raise ValueError("tokens/components.json is missing Cadence media presentation metrics")

    layout = profile.get("layout")
    if not isinstance(layout, dict):
        raise ValueError("Cadence must declare its layout metrics")
    required_layout = (
        "textStack",
        "compactGap",
        "controlGap",
        "contentGap",
        "panelInset",
        "pageInset",
        "sectionGap",
        "rowHeight",
        "readableContentWidth",
    )
    missing = [name for name in required_layout if not isinstance(layout.get(name), (int, float))]
    if missing:
        raise ValueError("Cadence layout is missing numeric metrics: " + ", ".join(missing))

    return "\n".join(
        [
            "// Generated by scripts/generate.py. Do not edit.",
            f"// Design System {products['meta']['version']}",
            "import Foundation",
            "",
            "public enum GeneratedProductProfiles {",
            "    public static let cadence = DesignProductMetrics(",
            *[
                f"        {swift_name(name)}: {layout[name]}{',' if index < len(required_layout) - 1 else ''}"
                for index, name in enumerate(required_layout)
            ],
            "    )",
            "}",
            "",
        ]
    )


def generate_token_reference(token_files: list[tuple[str, dict[str, Any]]]) -> str:
    lines = [
        "# Generated token reference",
        "",
        "Generated by `scripts/generate.py`. Do not edit directly.",
        "",
    ]
    for filename, data in token_files:
        lines.extend([f"## {data['meta']['name']}", "", data["meta"]["description"], ""])
        for name, value in sorted(flatten({k: v for k, v in data.items() if k not in {"$schema", "meta"}}).items()):
            display = json.dumps(value, ensure_ascii=False) if not isinstance(value, str) else value
            lines.append(f"- `{name}`: `{display}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_swift_icons(registry: dict[str, Any]) -> str:
    cases = [f'    case {swift_name(item["id"])} = "{item["sfSymbol"]}"' for item in registry["icons"]]
    return "\n".join(
        [
            "// Generated by scripts/generate.py. Do not edit.",
            f"// Design System {registry['version']}",
            "",
            "public enum DesignIcon: String, CaseIterable, Sendable {",
            *cases,
            "",
            "    public var systemName: String { rawValue }",
            "}",
            "",
        ]
    )
