"""Token loading, reference resolution, and platform adapter generation."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


REFERENCE = re.compile(r"^\{([^}]+)}$")


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def get_path(mapping: dict[str, Any], dotted: str) -> Any:
    current: Any = mapping
    for segment in dotted.split("."):
        if not isinstance(current, dict) or segment not in current:
            raise KeyError(f"Unknown token reference: {dotted}")
        current = current[segment]
    return current


def resolve(value: Any, foundation: dict[str, Any]) -> Any:
    if isinstance(value, str):
        match = REFERENCE.match(value)
        if match:
            return resolve(get_path(foundation, match.group(1)), foundation)
    return value


def kebab(value: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value)
    return re.sub(r"[^a-zA-Z0-9]+", "-", value).strip("-").lower()


def swift_name(value: str) -> str:
    parts = [part for part in re.split(r"[^a-zA-Z0-9]+", value) if part]
    first = parts[0]
    identifier = first[:1].lower() + first[1:] + "".join(part[:1].upper() + part[1:] for part in parts[1:])
    keywords = {
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
        "init", "inout", "internal", "let", "open", "operator", "private", "protocol", "public",
        "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "continue",
        "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat",
        "return", "switch", "where", "while", "as", "catch", "false", "is", "nil", "super",
        "self", "Self", "throw", "throws", "true", "try",
    }
    return f"`{identifier}`" if identifier in keywords else identifier


def flatten(mapping: dict[str, Any], prefix: tuple[str, ...] = ()) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in mapping.items():
        path = (*prefix, key)
        if isinstance(value, dict):
            result.update(flatten(value, path))
        else:
            result[".".join(path)] = value
    return result


def css_value(value: Any) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return f"{value}px"
    return str(value)


def generate_css(
    foundation: dict[str, Any],
    semantic: dict[str, Any],
    typography: dict[str, Any],
    motion: dict[str, Any],
    components: dict[str, Any],
) -> str:
    light = flatten(semantic["modes"]["light"])
    dark = flatten(semantic["modes"]["dark"])
    type_roles = typography["roles"]

    def mode_lines(values: dict[str, Any]) -> list[str]:
        return [
            f"  --qds-{kebab(name)}: {css_value(resolve(value, foundation))};"
            for name, value in sorted(values.items())
        ]

    lines = [
        "/* Generated by scripts/build.py. Do not edit. */",
        f"/* QenTerra Design System {foundation['meta']['version']} */",
        ":root, [data-theme=\"light\"] {",
        *mode_lines(light),
    ]

    for name, value in flatten(
        {key: foundation[key] for key in ("space", "radius", "stroke", "size")}
    ).items():
        lines.append(f"  --qds-{kebab(name)}: {css_value(value)};")
    for name, value in flatten({key: foundation[key] for key in ("opacity", "zIndex")}).items():
        lines.append(f"  --qds-{kebab(name)}: {value};")

    for name, role in type_roles.items():
        role_name = kebab(name)
        family = role.get("family", "sans")
        lines.extend(
            [
                f"  --qds-type-{role_name}-size: {role['size']}px;",
                f"  --qds-type-{role_name}-line: {role['line']}px;",
                f"  --qds-type-{role_name}-weight: {role['weight']};",
                f"  --qds-type-{role_name}-tracking: {role['tracking']}px;",
                f"  --qds-type-{role_name}-family: {typography['family'][family]};",
            ]
        )

    for name, value in motion["durationMs"].items():
        lines.append(f"  --qds-motion-{kebab(name)}: {value}ms;")
    for name, curve in motion["curve"].items():
        lines.append(f"  --qds-ease-{kebab(name)}: cubic-bezier({', '.join(str(v) for v in curve)});")
    for name, value in sorted(
        flatten({key: value for key, value in components.items() if key not in {"$schema", "meta", "extensions"}}).items()
    ):
        if isinstance(value, str) and REFERENCE.match(value):
            value = resolve(value, foundation)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            lines.append(f"  --qds-component-{kebab(name)}: {css_value(value)};")
    lines.append("}")

    lines.extend(["[data-theme=\"dark\"] {", *mode_lines(dark), "}"])
    lines.extend(
        [
            "@media (prefers-color-scheme: dark) {",
            "  :root:not([data-theme=\"light\"]):not([data-theme=\"dark\"]) {",
            *[f"  {line}" for line in mode_lines(dark)],
            "  }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def generate_swift(
    foundation: dict[str, Any],
    semantic: dict[str, Any],
    typography: dict[str, Any],
    motion: dict[str, Any],
    components: dict[str, Any],
) -> str:
    space = foundation["space"]
    radius = foundation["radius"]
    stroke = foundation["stroke"]
    sizes = foundation["size"]
    durations = motion["durationMs"]

    def constants(mapping: dict[str, Any], multiplier: str = "") -> list[str]:
        result = []
        for name, value in mapping.items():
            identifier = swift_name(f"value{name}") if name[0].isdigit() else swift_name(name)
            result.append(f"        public static let {identifier}: Double = {value}{multiplier}")
        return result

    color_light = flatten(semantic["modes"]["light"])
    color_dark = flatten(semantic["modes"]["dark"])

    color_lines = []
    for name in sorted(color_light):
        light = resolve(color_light[name], foundation)
        dark = resolve(color_dark[name], foundation)
        color_lines.append(
            f'        public static let {swift_name(name)} = QDSColorValue(light: "{light}", dark: "{dark}")'
        )

    typography_lines = []
    for name, role in typography["roles"].items():
        family = role.get("family", "sans")
        transform = role.get("transform")
        numeric = role.get("numeric")
        typography_lines.append(
            "        public static let "
            f"{swift_name(name)} = QDSTypographyValue("
            f"family: {json.dumps(typography['family'][family])}, size: {role['size']}, "
            f"lineHeight: {role['line']}, weight: {role['weight']}, tracking: {role['tracking']}, "
            f"transform: {json.dumps(transform) if transform else 'nil'}, "
            f"numeric: {json.dumps(numeric) if numeric else 'nil'})"
        )

    motion_lines = []
    for name, event in motion["events"].items():
        duration = motion["durationMs"][event["duration"]] / 1000
        curve = motion["curve"][event["curve"]]
        properties = ", ".join(json.dumps(item) for item in event["properties"])
        motion_lines.append(
            f"        public static let {swift_name(name)} = QDSMotionValue("
            f"seconds: {duration:g}, curve: [{', '.join(f'{item:g}' for item in curve)}], "
            f"properties: [{properties}])"
        )

    component_values = flatten(
        {key: value for key, value in components.items() if key not in {"$schema", "meta", "extensions"}}
    )
    component_lines = []
    for name, value in sorted(component_values.items()):
        if isinstance(value, str) and REFERENCE.match(value):
            value = resolve(value, foundation)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            component_lines.append(
                f"        public static let {swift_name(name)} = QDSComponentMetric(points: {value})"
            )

    return "\n".join(
        [
            "// Generated by scripts/build.py. Do not edit.",
            f"// QenTerra Design System {foundation['meta']['version']}",
            "import Foundation",
            "",
            "public enum QDSGeneratedTokens {",
            f'    public static let version = "{foundation["meta"]["version"]}"',
            "",
            "    public enum Space {",
            *constants(space),
            "    }",
            "",
            "    public enum Radius {",
            *constants(radius),
            "    }",
            "",
            "    public enum Stroke {",
            *constants(stroke),
            "    }",
            "",
            "    public enum Size {",
            *constants(sizes),
            "    }",
            "",
            "    public enum MotionSeconds {",
            *constants({key: round(value / 1000, 3) for key, value in durations.items()}),
            "    }",
            "",
            "    public enum SemanticName {",
            *[
                f'        public static let {swift_name(name)} = "{name}"'
                for name in sorted(flatten(semantic["modes"]["light"]))
            ],
            "    }",
            "",
            "    public enum Color {",
            *color_lines,
            "    }",
            "",
            "    public enum Typography {",
            *typography_lines,
            "    }",
            "",
            "    public enum Motion {",
            *motion_lines,
            "    }",
            "",
            "    public enum Component {",
            *component_lines,
            "    }",
            "}",
            "",
        ]
    )


def generate_token_reference(token_files: list[tuple[str, dict[str, Any]]]) -> str:
    lines = [
        "# Generated token reference",
        "",
        "Generated by `scripts/build.py`. Do not edit directly.",
        "",
    ]
    for filename, data in token_files:
        lines.extend([f"## {data['meta']['name']}", "", data["meta"]["description"], ""])
        for name, value in sorted(flatten({k: v for k, v in data.items() if k not in {"$schema", "meta"}}).items()):
            display = json.dumps(value, ensure_ascii=False) if not isinstance(value, str) else value
            lines.append(f"- `{name}`: `{display}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_swift_icons(registry: dict[str, Any]) -> str:
    cases = [f'    case {swift_name(item["id"])} = "{item["id"]}"' for item in registry["icons"]]
    return "\n".join(
        [
            "// Generated by scripts/build.py. Do not edit.",
            f"// QenTerra Design System {registry['version']}",
            "",
            "public enum QDSIcon: String, CaseIterable, Sendable {",
            *cases,
            "}",
            "",
        ]
    )


def generate_svg_sprite(registry: dict[str, Any]) -> str:
    symbols = [
        f'<symbol id="qds-icon-{item["id"]}" viewBox="{registry["viewBox"]}">{item["svg"]}</symbol>'
        for item in registry["icons"]
    ]
    return "\n".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="display:none">',
            *symbols,
            "</svg>",
            "",
        ]
    )
